import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { apiGet, PROJECT_REF } from "./config-api";
import { extractRemote } from "./config-managed";

const here = dirname(fileURLToPath(import.meta.url));
const snapshotPath = join(here, ".remote-config.json");
const remoteTomlPath = join(here, "config.toml.remote");

const ENDPOINTS = [
  { name: "project", path: "" },
  { name: "auth", path: "/config/auth" },
  { name: "postgrest", path: "/postgrest" },
  { name: "db_postgres", path: "/config/database/postgres" },
  { name: "db_pooler", path: "/config/database/pooler" },
  { name: "storage", path: "/config/storage" },
];

function renderRemoteToml(auth: Record<string, unknown>): string {
  const lines = [
    "# OBSERVED remote state — generated by `npm run config:pull`. Do not edit (gitignored).",
    "# Desired state lives in config.toml. Compare with `npm run config:diff`.",
    "",
    "[managed]",
  ];
  for (const { id, display } of extractRemote(auth)) {
    lines.push(`${id} = ${JSON.stringify(display)}`);
  }
  return lines.join("\n") + "\n";
}

async function main() {
  console.error(`Pulling live config for project ${PROJECT_REF}\n`);

  const snapshot: Record<string, unknown> = {};
  for (const { name, path } of ENDPOINTS) {
    const { status, ok, body } = await apiGet(path);
    snapshot[name] = ok ? body : { _error: status };
    console.error(`  ${ok ? "ok " : "ERR"} ${status}  ${name}${path || " (meta)"}`);
  }

  writeFileSync(snapshotPath, JSON.stringify(snapshot, null, 2), "utf8");

  const auth = snapshot.auth as Record<string, unknown>;
  writeFileSync(remoteTomlPath, renderRemoteToml(auth), "utf8");

  console.error(`\nWrote:`);
  console.error(`  ${snapshotPath}  (raw snapshot of all endpoints)`);
  console.error(`  ${remoteTomlPath}  (managed-field observed state)`);
  console.error(`\nNext: npm run config:diff`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
