[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_22", "python3", "ffmpeg"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci", "pip3 install --no-cache-dir yt-dlp"]

[build.nixpacksPlan.phases.build]
cmds = ["npx prisma generate", "npm run build"]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300
