-- The welcome-back greeting must fit YouTube's 200-character limit alongside a
-- mention and a link, while the cached !me bio runs to about 550 characters.
-- Truncating the bio to fit would cut it mid-sentence.
--
-- Instead the same Claude call that writes the bio also writes a one-line
-- welcome, cached in the same row and regenerated by the same rules, so the
-- greeting and the !me reply can never describe someone differently.

alter table public.me_profiles
  add column if not exists short_line text;
